services:
  web:
    image: '${GITLAB_IMAGE:-gitlab/gitlab-ee:latest}'
    restart: always
    hostname: '${HOSTNAME:-localhost}' # Default hostname to 'localhost' if not set
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${EXTERNAL_URL:-http://localhost}'
    ports:
      - '${HTTP_PORT:-8013}:80' # Use 8013 as default HTTP port
      - '${SSL_PORT:-4443}:443' # SSL port (default 4443)
      - '${SSH_PORT:-2222}:22' # Use 2222 as default SSH port
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
