services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    # Local setup
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
    ports:
      - '8013:80'   # Local HTTP port
      # - '443:443' # Commented out as not used locally
      - '2222:22'   # Local SSH port
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
